### ISSUE TITLE
bad interaction with invidious?

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/chatonsinfos_ynh#6]
hello, 
today i tried to upgrade invidious,  
but it seems chatonsinfos and invidious are in conflict (?) and invidious was uninstalled :/

https://paste.yunohost.org/raw/okuqagagiy

auto restoration failed, 
i can't figure if the issue is only on invidious side , or if chatonsinfos is involved
```
Success! invidious uninstalled
Warning: YunoHost is already installed
Info: Preparing archive for restoration...
Info: Restoring invidious...
Warning: Failed to get label for app invidious ?
Warning: File /var/www/chatonsinfos/public/invidious.properties does not exists
Warning: File /var/www/chatonsinfos/public/invidious.properties does not exists
Error: Could not run script: /etc/yunohost/hooks.d/post_app_addaccess/50-chatonsinfos
```

and restoration is KO:
```
root@krashboyz:~# yunohost backup restore invidious-pre-upgrade2
Warning: YunoHost is already installed
Do you really want to restore an already installed system? [y/N]: y
Info: Preparing archive for restoration...
Info: Restoring invidious...
Warning: Failed to get label for app invidious ?
Warning: File /var/www/chatonsinfos/public/invidious.properties does not exists
Warning: File /var/www/chatonsinfos/public/invidious.properties does not exists
Error: Could not run script: /etc/yunohost/hooks.d/post_app_addaccess/50-chatonsinfos
Warning: File /var/www/chatonsinfos/public/invidious.properties does not exists
Warning: File /var/www/chatonsinfos/public/invidious.properties does not exists
Error: Could not run script: /etc/yunohost/hooks.d/post_app_addaccess/50-chatonsinfos
Warning: File /var/www/chatonsinfos/public/invidious.properties does not exists
Warning: File /var/www/chatonsinfos/public/invidious.properties does not exists
Error: Could not run script: /etc/yunohost/hooks.d/post_app_addaccess/50-chatonsinfos
Info: Provisioning system_user...
Info: Provisioning install_dir...
Info: Provisioning ports...
Info: Provisioning permissions...
Info: Provisioning apt...
Info: Provisioning database...
Info: [....................] > Restoring the NGINX configuration...
Info: [++++................] > Restoring the app main directory...
Info: [####+++++++.........] > Reinstalling dependencies...
Warning: E: Unable to correct problems, you have held broken packages.
Error: Could not restore invidious: An error occured inside the app restore script
Info: The operation 'Restore 'invidious' from a backup archive' could not be completed. Please share the full log of this operation using the command 'yunohost log share 20240112-115311-backup_restore_app-invidious' to get help
Error: Could not restore invidious: Something unexpected went wrong: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yunohost/hook.py", line 542, in hook_exec_with_script_debug_if_failure
    operation_logger.dump_script_log_extract_for_debugging()
  File "/usr/lib/python3/dist-packages/yunohost/log.py", line 749, in dump_script_log_extract_for_debugging
    lines = [line.strip().split(": ", 1)[1] for line in lines]
  File "/usr/lib/python3/dist-packages/yunohost/log.py", line 749, in <listcomp>
    lines = [line.strip().split(": ", 1)[1] for line in lines]
IndexError: list index out of range

Info: Removing invidious...
Info: [++++++++++++++++....] > Removing system configurations related to invidious...
Warning: dpkg: warning: ignoring request to remove crystal which isn't installed
Info: '/etc/cron.d/invidious' wasn't deleted because it doesn't exist.
Info: [####################] > Removal of Invidious completed
Info: Deprovisioning database...
Info: Deprovisioning apt...
Info: Deprovisioning permissions...
Info: Deprovisioning ports...
Info: Deprovisioning install_dir...
Info: Deprovisioning system_user...
Success! invidious uninstalled
Info: '/var/www/chatonsinfos//public/invidious.properties' wasn't deleted because it doesn't exist.
Error: None
Error: Nothing was restored
```

**Comment by isAAAc** [comment]
i tried a workaround removing chatonsinfos and then trying to restore invidous, but it fails too :/
https://paste.yunohost.org/raw/kumiyekowa

i'm a bit lost

i think the trouble isn't chatonsinfos but invidious: reinstall is failing too:
https://paste.yunohost.org/raw/wujibukebe

i'll open an issue on invidious_ynh side
edit: and close this present one :)
